name: Deploy nodejscicddockerhub


on:
 push:
   branches:
     - main


jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout Source
       uses: actions/checkout@v4


    
     - name: Use Node.js 20
       uses: actions/setup-node@v3
       
       with:
         node-version: '20'  # Specify the Node.js version


     - name: Install dependencies
       run: npm ci


     - name: Build Docker Image
       run: docker build -t shakilpro/youtubenode-backend:latest .


     - name: Push Docker Image to Docker Hub
       run: |
         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
         docker push shakilpro/youtubenode-backend:latest


 deploy:
   runs-on: self-hosted
   needs: build
   steps:
     - name: Checkout Source
       uses: actions/checkout@v4


     - name: Login to Docker Hub
       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


     - name: Pull Image from Docker Hub
       run: docker pull shakilpro/youtubenode-backend:latest


     - name: Delete Old Container
       run: |
         if [ $(docker ps -aq -f name=shakilpro/youtubenode-backend-container) ]; then
           docker rm -f youtubenode-backend-container
         fi


     - name: Run Docker Container
       run: docker run -d -p 4001:4000 --name youtubenode-backend-container -e MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" shakilpro/youtubenode-backend:latest
